version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - tailwind

  tailwind:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "cd frontend && npm install && npm run dev"
